namespace Network
{
    class Fuel
    {
        public int cost;
        public int pollutionProduction;
        public int energyProduction;
        
        public Fuel(int cost, int pollutionProduction,int energyProduction)
        {
            /* 
            Variables :
            int cost = Price to buy at the unit
            int pollutionProduction : CO2 quantity produced by unit
            int energyProduction : Power generated by unit
            */
            this.cost = cost;
            this.pollutionProduction = pollutionProduction;
            this.energyProduction = energyProduction;
            
        }
        public int getCost()
        {
            return this.cost;
        }
        public int getPollution()
        {
            return this.pollutionProduction;
        }
        public int getEnergy()
        {
            return this.energyProduction;
        }
        
    }
}
