namespace Network
{
    class Fuel
    {
        public int costPerUnit;
        public int pollutionPerUnit;
        public int energyPerUnit;
        
        public Fuel(int costPerUnit, int pollutionPerUnit,int energyPerUnit)
        {
            /* 
            Variables :
            int cost = Price to buy at the unit
            int pollutionProduction : CO2 quantity produced by unit
            int energyProduction : Power generated by unit
            */
            this.costPerUnit = costPerUnit;
            this.pollutionPerUnit = pollutionPerUnit;
            this.energyPerUnit = energyPerUnit;
            
        }
        public int getCost()
        {
            return this.costPerUnit;
        }
        public int getPollution()
        {
            return this.pollutionPerUnit;
        }
        public int getEnergy()
        {
            return this.energyPerUnit;
        }
        
    }
}
